// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzjzxckxaiwneybyduim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6anp4Y2t4YWl3bmV5YnlkdWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTc5ODEsImV4cCI6MjA2OTM5Mzk4MX0.QDlt6Y5ITwZ0kjQOvIsMvDG11lUMvxpDnm83T50tHuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});